# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 11:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ("bot_control", "0002_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2017, 6, 24, 11, 58, 8, 972245, tzinfo=utc)
            ),
            preserve_default=False,
        ),
    ]
