# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("bot_control", "0003_channel_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="users",
            field=models.ManyToManyField(to="bot_control.User"),
        ),
        migrations.AlterField(
            model_name="channel",
            name="time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
