# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bot_control", "0004_auto_20170624_2011"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="channel",
            name="users",
        ),
        migrations.AddField(
            model_name="message",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bot_control.Channel"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bot_control.User"
            ),
        ),
    ]
