# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot_control', '0005_auto_20170624_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.IntegerField(default=-1),
        ),
    ]
