# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_control', '0006_auto_20170703_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tweets_counter',
            field=models.IntegerField(default=0),
        ),
    ]
