# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_control', '0007_user_tweets_counter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tweets_counter',
            new_name='tweet_counter',
        ),
    ]
