# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_control', '0008_auto_20170704_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
